Feature/canon camera
Motiony/MPhotoBoothAI pull request #14
Opened 2024-11-03 17:49 UTC by MrRadian

Add support form Canon cameras
Add Camera settings view to easier manipulate camera settings

https://trello.com/c/jZplTmEs

2024-11-04 15:08 UTC, matihuf requested changes

2024-11-04 15:47 UTC, MrRadian commented on .gitignore
> +models/arcface_backbone.onnx
wywalone

2024-11-04 15:49 UTC, MrRadian commented on src/MPhotoBoothAI.Application/Assets/UI.en-US.resx
> +    <value> Your camera name</value>
poprawione

2024-11-04 15:50 UTC, MrRadian commented on src/MPhotoBoothAI.Application/Managers/CameraManager.cs
> +namespace MPhotoBoothAI.Infrastructure.Services
poprawione

2024-11-04 16:59 UTC, MrRadian commented on src/MPhotoBoothAI.Application/ViewModels/CameraSettingsViewModel.cs
> +            if (newValue != null && _databaseContext.CameraSettings.Any(s => s.Camera == newValue.CameraName) && newValue is ICameraDeviceSettings settings)
wywalone

2024-11-04 17:17 UTC, MrRadian commented on src/MPhotoBoothAI.Application/ViewModels/CameraSettingsViewModel.cs
> +            if (e.PropertyName == "Manual")
wywalone

2024-11-04 17:21 UTC, MrRadian commented on src/MPhotoBoothAI.Application/ViewModels/FaceDetectionViewModel.cs
> +        _faceMultiSwapManager = faceSwapManager;
coś poszło nie tak bo nie ruszałem tego specjalnie

2024-11-04 17:41 UTC, MrRadian commented on src/MPhotoBoothAI.Avalonia/Extensions/MatExtensions.cs
zrobione

2024-11-04 17:42 UTC, MrRadian commented on src/MPhotoBoothAI.Avalonia/MPhotoBoothAI.Avalonia.csproj
> +    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.10" />
na ten moment nie, wywalona

2024-11-05 18:38 UTC, MrRadian commented on src/MPhotoBoothAI.Camera.Canon/MPhotoBoothAI.Camera.Canon.csproj
wywalony

2024-11-05 19:33 UTC, MrRadian commented on tests/MPhotoBoothAI.Integration.Tests/ViewModels/CameraSettingsViewModelTests.cs
> +namespace MPhotoBoothAI.Integration.Tests.ViewModels
przeniesiony, dodany

2024-11-05 19:38 UTC, MrRadian commented on tests/MPhotoBooth.Unit.Tests/Application/Managers/CameraManagerTests.cs
> +namespace MPhotoBooth.Unit.Tests.Application.Managers
dodany

2024-11-05 19:39 UTC, MrRadian commented on src/MPhotoBoothAI.Application/MPhotoBoothAI.Application.csproj
> +    <Folder Include="Enums\" />
wywalony

2024-11-05 19:39 UTC, MrRadian commented on src/MPhotoBoothAI.Application/Interfaces/ICameraManager.cs
> +
wywalony

2024-11-05 19:41 UTC, MrRadian commented on src/MPhotoBoothAI.Infrastructure/Persistence/Migrations/20241102160550_AddCameraNameInDatabase.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
migracje  połączone i dodane jako jedna

2024-11-05 19:45 UTC, MrRadian commented on src/MPhotoBoothAI.Infrastructure/CameraDevices/CanonCameraDevice.cs
> +            _logger.Log(LogLevel.Information, $"Canon SDK error: {Enum.GetName(typeof(CameraErrorCodes), (long)e)}");
tego to się nie spodziewałem, poprawione

2024-11-05 19:55 UTC, MrRadian commented on src/MPhotoBoothAI.Application/Interfaces/ICameraDevice.cs
>  namespace MPhotoBoothAI.Application.Interfaces;
zmieniłem w ustawieniach, gdzie zauważę to porawię

2024-11-05 19:55 UTC, MrRadian commented on src/MPhotoBoothAI.Infrastructure/CameraDevices/CanonCameraDevice.cs
> +        private void _sdkHandler_SdkErrorEvent(object? sender, uint e)
zmieniona

2024-11-05 20:01 UTC, MrRadian commented on src/MPhotoBoothAI.Application/ViewModels/CameraSettingsViewModel.cs
> +            CameraSettings = newValue is ICameraDeviceSettings cameraDeviceSettings ? cameraDeviceSettings : null;
ok

2024-11-06 06:19 UTC, matihuf requested changes

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Application/MPhotoBoothAI.Application.csproj
> +    <Folder Include="Enums\" />
dalej jest dodany

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Application/ViewModels/MainViewModel.cs
> +        new ListItemTemplate(typeof(CameraSettingsViewModel), "camera_regular", "CameraSettings"),
Dodaj tłumaczenie dla CamerSettings

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Avalonia/Styles/Icons.axaml
> +			<StreamGeometry x:Key="camera_regular">M16.9510797,2.50304787 C17.7274884,2.50304787 18.4490393,2.9033378 18.8600157,3.56205529 L20.3810589,6 L22.75,6 C24.5449254,6 26,7.45507456 26,9.25 L26,21.75
Brak formatowania w pliku po dodaniu nowej ikony

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Avalonia/Views/CameraSettingsView.axaml
> +			 xmlns:vm="using:MPhotoBoothAI.Application.ViewModels"
![obraz](https://github.com/user-attachments/assets/0d6900b9-d020-4e4d-b460-15f4c3929854)
dalej są schodu w usingach, ciężko się na to patrzy

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Avalonia/Views/CameraSettingsView.axaml
> +<UserControl xmlns="https://github.com/avaloniaui"
![obraz](https://github.com/user-attachments/assets/3a9c762a-79c2-4c08-99a9-0bfe098e2826)
dodaj jakieś odstępy pomiędzy kontrolkami

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Avalonia/Views/MainWindow.axaml
> +        Title="MPhotoBoothAI"
![obraz](https://github.com/user-attachments/assets/c0e72eae-a3a9-456c-a8a3-a857335e8783)
kod do sformatowania

2024-11-06 06:19 UTC, matihuf commented on src/MPhotoBoothAI.Infrastructure/Persistence/Migrations/20241105194048_AddCameraNameInDatabase.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
pusta migracja?

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/Builders/CameraSettingsViewModelBuilder.cs
> +            // Inicjalizacja pustych list i mocków
fajne te komentarze od czata ale nie potrzebne

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/CameraSettingsViewModelTests.cs
> +            // Ustawienie początkowego urządzenia, aby zdarzenie PropertyChanged było dodane i można było je usunąć
tutaj też nie potrzebny

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/CameraSettingsViewModelTests.cs
> +            // Act - zmiana urządzenia
tutaj też nie potrzebny

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/CameraSettingsViewModelTests.cs
> +            // Weryfikacja przypisania i usunięcia zdarzenia PropertyChanged
tutaj też nie potrzebny

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/CameraSettingsViewModelTests.cs
> +
pusta linia

2024-11-06 06:19 UTC, matihuf commented on tests/MPhotoBooth.Unit.Tests/Application/ViewModels/CameraSettingsViewModelTests.cs
> +
2 puste linie

2024-11-07 18:50 UTC, MrRadian commented on src/MPhotoBoothAI.Avalonia/Views/CameraSettingsView.axaml
> +<UserControl xmlns="https://github.com/avaloniaui"
dodany

2024-11-07 18:57 UTC, MrRadian commented on src/MPhotoBoothAI.Application/ViewModels/MainViewModel.cs
> +        new ListItemTemplate(typeof(CameraSettingsViewModel), "camera_regular", "CameraSettings"),
dodałem, czy to jest już ładnie ogarnięte, że w menu pojawią się tłumaczenia?

2024-11-07 19:00 UTC, MrRadian commented on src/MPhotoBoothAI.Avalonia/App.axaml.cs
> +
wywalona

2024-11-07 19:00 UTC, MrRadian commented on src/MPhotoBoothAI.Application/MPhotoBoothAI.Application.csproj
> +    <Folder Include="Enums\" />
teraz wywalony też csproj

2024-11-07 19:00 UTC, MrRadian commented on src/MPhotoBoothAI.Models/MPhotoBoothAI.Models.csproj
> +	  <Folder Include="Camera\" />
wywalony z csproj

2024-11-07 19:02 UTC, MrRadian commented on src/MPhotoBoothAI.Avalonia/Views/CameraSettingsView.axaml
> +			 xmlns:vm="using:MPhotoBoothAI.Application.ViewModels"
![obraz](https://github.com/user-attachments/assets/36d5963f-90de-4897-9553-1ec166dd2faf)
tak jest u mnie, nwm czemu.
Ty to masz w vs code?

2024-11-09 07:32 UTC, merged